'use client';

/** Block-level parser for narrative / session-page content.
 *
 * This intentionally mirrors the shape of SmartBlock from
 * ./smart-document-editor but adds structural recognition for fenced code
 * blocks (```mermaid, etc.) and markdown tables. It is used by
 * NarrativeViewer and SessionPageEditor so both stay aligned on how the
 * standard envelope's narrative content is split and indexed.
 */

export interface NarrativeBlock {
  id: string;
  type: 'text' | 'heading' | 'image' | 'code' | 'table';
  raw: string;
  edited?: string;
  deleted?: boolean;
  level?: number;
  title?: string;
  language?: string;
  /** True when the heading was generated by the envelope renderer and is not a real narrative section. */
  synthetic?: boolean;
  /** When set, the original index of this narrative in the envelope's narratives array. */
  __narrativeIdx?: number;
}

/** Headings that are generated by buildEnvelopeMarkdown to label structured data.
 *  They are not real narrative sections and should not appear in the section index. */
const SYNTHETIC_HEADING_PREFIXES = [
  'Table:',
  'Graph:',
  'Diagram:',
  'Source:',
  'Generated:',
  'Raw JSON',
  'mermaid',
];

const SYNTHETIC_HEADING_EXACTS = ['Graph'];

export function isSyntheticHeading(title?: string): boolean {
  if (!title) return false;
  const trimmed = title.trim();
  if (SYNTHETIC_HEADING_EXACTS.includes(trimmed)) return true;
  return SYNTHETIC_HEADING_PREFIXES.some((prefix) =>
    trimmed === prefix || trimmed.startsWith(`${prefix} `)
  );
}

function flushText(textBuffer: string[], blocks: NarrativeBlock[], blockId: { value: number }) {
  if (textBuffer.length) {
    blocks.push({
      id: `b${blockId.value++}`,
      type: 'text',
      raw: textBuffer.join('\n') + '\n',
    });
    textBuffer.length = 0;
  }
}

export interface ParseNarrativeBlocksOptions {
  /** Attach the original narrative array index to each non-synthetic heading. */
  attachNarrativeIdx?: boolean;
}

export function parseNarrativeBlocks(content: string, options?: ParseNarrativeBlocksOptions): NarrativeBlock[] {
  const blocks: NarrativeBlock[] = [];
  const lines = content.split(/\n/);
  const textBuffer: string[] = [];
  const blockId = { value: 0 };
  let narrativeIdx = 0;

  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    const headingMatch = line.match(/^(#{1,6})\s+(.+)$/);
    const imageOpenMatch = line.match(/^\[IMAGE:([^\]]+)\]$/);
    const codeFenceMatch = line.match(/^```(\w*)\s*$/);
    const tableMatch = (line.match(/\|/g) || []).length >= 2;

    if (headingMatch) {
      flushText(textBuffer, blocks, blockId);
      const title = headingMatch[2];
      const synthetic = isSyntheticHeading(title);
      const heading: NarrativeBlock = {
        id: `b${blockId.value++}`,
        type: 'heading',
        raw: line + '\n',
        level: headingMatch[1].length,
        title,
        synthetic,
      };
      if (!synthetic && options?.attachNarrativeIdx) {
        heading.__narrativeIdx = narrativeIdx++;
      }
      blocks.push(heading);
      i++;
    } else if (imageOpenMatch) {
      flushText(textBuffer, blocks, blockId);
      const imageId = imageOpenMatch[1];
      const imageLines: string[] = [line];
      let j = i + 1;
      while (j < lines.length) {
        const closeMatch = lines[j].match(
          new RegExp(`^\\[/IMAGE:${imageId.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\]$`)
        );
        imageLines.push(lines[j]);
        if (closeMatch) break;
        j++;
      }
      blocks.push({
        id: `b${blockId.value++}`,
        type: 'image',
        raw: imageLines.join('\n') + '\n',
        title: imageId,
      });
      i = j + 1;
    } else if (codeFenceMatch) {
      flushText(textBuffer, blocks, blockId);
      const language = codeFenceMatch[1];
      const codeLines: string[] = [line];
      let j = i + 1;
      while (j < lines.length) {
        codeLines.push(lines[j]);
        if (lines[j].match(/^```\s*$/)) break;
        j++;
      }
      blocks.push({
        id: `b${blockId.value++}`,
        type: 'code',
        raw: codeLines.join('\n') + '\n',
        title: language || 'code',
        language,
      });
      i = j + 1;
    } else if (tableMatch) {
      flushText(textBuffer, blocks, blockId);
      const tableLines: string[] = [line];
      let j = i + 1;
      while (j < lines.length && (lines[j].match(/\|/g) || []).length >= 2) {
        tableLines.push(lines[j]);
        j++;
      }
      blocks.push({
        id: `b${blockId.value++}`,
        type: 'table',
        raw: tableLines.join('\n') + '\n',
        title: tableLines[0]?.replace(/\|/g, ' ').trim() || 'table',
      });
      i = j;
    } else {
      textBuffer.push(line);
      i++;
    }
  }
  flushText(textBuffer, blocks, blockId);
  return blocks;
}

export function buildNarrativeContent(blocks: NarrativeBlock[]): string {
  return blocks.filter((b) => !b.deleted).map((b) => b.edited ?? b.raw).join('');
}

export function buildUserNarrativeContent(blocks: NarrativeBlock[]): string {
  // Drop synthetic headings and every block that lives under a synthetic heading,
  // even if the blocks themselves are not marked synthetic (e.g. legacy graph JSON
  // that was previously stored inside synthesis.narrative).
  const syntheticSubtreeIds = new Set<string>();
  for (const b of blocks) {
    if (b.type === 'heading' && b.synthetic) {
      for (const id of getSectionBlockIds(blocks, b.id)) {
        syntheticSubtreeIds.add(id);
      }
    }
  }
  return blocks
    .filter((b) => !b.deleted && !b.synthetic && !syntheticSubtreeIds.has(b.id))
    .map((b) => b.edited ?? b.raw)
    .join('');
}

export function getSectionBlockIds(blocks: NarrativeBlock[], targetId: string): string[] {
  const idx = blocks.findIndex((b) => b.id === targetId);
  if (idx === -1) return [];
  const target = blocks[idx];
  if (target.type !== 'heading') return [targetId];
  const ids = [targetId];
  for (let i = idx + 1; i < blocks.length; i++) {
    const b = blocks[i];
    if (b.type === 'heading' && b.level! <= target.level!) break;
    ids.push(b.id);
  }
  return ids;
}

export function getSidebarIndent(blocks: NarrativeBlock[], index: number): number {
  const block = blocks[index];
  if (block.type === 'heading') return block.level! - 1;
  for (let i = index - 1; i >= 0; i--) {
    if (blocks[i].type === 'heading') {
      return blocks[i].level!;
    }
  }
  return 0;
}
