'use client';

import { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Loader2, Lock } from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';
import { metadataApi, type Metadata } from '@/lib/api/client';
import { toast } from 'sonner';

interface ViewMetadataDialogProps {
  metadata: Metadata | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onMetadataUpdated?: () => void;
}

export function ViewMetadataDialog({
  metadata,
  open,
  onOpenChange,
  onMetadataUpdated,
}: ViewMetadataDialogProps) {
  const [isSaving, setIsSaving] = useState(false);
  const [key, setKey] = useState('');
  const [value, setValue] = useState('');

  const isSystem = metadata?.generated_by === 'system';

  useEffect(() => {
    if (metadata) {
      setKey(metadata.key || '');
      setValue(metadata.value || '');
    }
  }, [metadata, open]);

  if (!metadata) return null;

  const hasChanges =
    !isSystem && (
      key !== (metadata.key || '') ||
      value !== (metadata.value || '')
    );

  const handleSave = async () => {
    if (isSystem) return;
    setIsSaving(true);
    try {
      const updates: Record<string, any> = {};

      if (key !== (metadata.key || '')) {
        updates.key = key || null;
      }
      if (value !== (metadata.value || '')) {
        updates.value = value || null;
      }

      if (Object.keys(updates).length > 0) {
        await metadataApi.update(metadata.id, updates);
        toast.success('Metadata updated');
        onMetadataUpdated?.();
        onOpenChange(false);
      }
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Update failed');
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle className="text-xl font-semibold text-white flex items-center gap-2">
            Metadata Details
            {isSystem && (
              <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-amber-900/30 border border-amber-500/30 text-amber-400 text-[10px] uppercase font-medium">
                <Lock className="h-3 w-3" />
                System Preset — Read Only
              </span>
            )}
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-6 py-4">
          {/* Editable Fields */}
          <div className="space-y-4">
            {/* Key */}
            <div className="space-y-2">
              <Label htmlFor="key" className="text-xs uppercase text-white/50 font-medium">
                Key
              </Label>
              <Input
                id="key"
                value={key}
                onChange={(e) => setKey(e.target.value)}
                placeholder="Enter key"
                disabled={isSystem}
                className="!rounded-lg !border !border-white/20 !bg-transparent !text-white !placeholder:text-white/40 focus:!border-emerald-400 focus:!ring-2 disabled:opacity-50 disabled:cursor-not-allowed"
                style={{
                  '--tw-ring-color': 'rgb(52, 211, 153)',
                  '--tw-ring-opacity': '0.4',
                } as React.CSSProperties}
              />
            </div>

            {/* Value */}
            <div className="space-y-2">
              <Label htmlFor="value" className="text-xs uppercase text-white/50 font-medium">
                Value
              </Label>
              <Input
                id="value"
                value={value}
                onChange={(e) => setValue(e.target.value)}
                placeholder="Enter value"
                disabled={isSystem}
                className="!rounded-lg !border !border-white/20 !bg-transparent !text-white !placeholder:text-white/40 focus:!border-emerald-400 focus:!ring-2 disabled:opacity-50 disabled:cursor-not-allowed"
                style={{
                  '--tw-ring-color': 'rgb(52, 211, 153)',
                  '--tw-ring-opacity': '0.4',
                } as React.CSSProperties}
              />
            </div>
          </div>

          {/* Read-only Metadata */}
          <div className="grid grid-cols-2 gap-4 pt-2 border-t border-white/10">
            <div className="space-y-1">
              <p className="text-xs uppercase text-white/50 font-medium">ID</p>
              <p className="text-sm text-white font-mono">{metadata.id}</p>
            </div>
            <div className="space-y-1">
              <p className="text-xs uppercase text-white/50 font-medium">Generated By</p>
              <p className="text-sm text-white font-mono capitalize">{metadata.generated_by}</p>
            </div>
            <div className="space-y-1">
              <p className="text-xs uppercase text-white/50 font-medium">Documents</p>
              <p className="text-sm text-white font-mono">
                {metadata.usage_count ? `${metadata.usage_count} document${metadata.usage_count !== 1 ? 's' : ''}` : 'None'}
              </p>
            </div>
            <div className="space-y-1">
              <p className="text-xs uppercase text-white/50 font-medium">Created</p>
              <p className="text-sm text-white/70">
                {formatDistanceToNow(new Date(metadata.created_at), { addSuffix: true })}
              </p>
            </div>
            <div className="space-y-1">
              <p className="text-xs uppercase text-white/50 font-medium">Updated</p>
              <p className="text-sm text-white/70">
                {formatDistanceToNow(new Date(metadata.updated_at), { addSuffix: true })}
              </p>
            </div>
          </div>

          {/* Hindsight sync warning */}
          {(metadata.usage_count ?? 0) > 0 && !isSystem && hasChanges && (
            <div className="flex items-start gap-2 p-3 rounded-lg bg-amber-900/20 border border-amber-500/30">
              <svg className="h-4 w-4 text-amber-400 mt-0.5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
              </svg>
              <p className="text-xs text-amber-300">
                This metadata is linked to {metadata.usage_count} document{metadata.usage_count !== 1 ? 's' : ''}. If any of these documents have already been synced to Hindsight, the updated key/value may cause a mismatch on the next sync.
              </p>
            </div>
          )}

          {/* Actions */}
          <div className="flex justify-end gap-3 pt-4 border-t border-white/10">
            <Button
              variant="ghost"
              onClick={() => onOpenChange(false)}
              className="text-white/70 hover:text-white hover:bg-white/5"
            >
              Close
            </Button>
            {!isSystem && (
              <Button
                onClick={handleSave}
                disabled={!hasChanges || isSaving}
                className="bg-emerald-600 hover:bg-emerald-500 text-white disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
              >
                {isSaving && <Loader2 className="h-4 w-4 animate-spin" />}
                {isSaving ? 'Saving...' : 'Save Changes'}
              </Button>
            )}
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
