-- ============================================================================
-- SYSTEM SEED DATA
-- ============================================================================
-- Idempotent inserts: INSERT OR IGNORE skips duplicates via the
-- UNIQUE(meta_key, meta_value) constraint on the metadata table.
-- These entries are tagged with generated_by='system' and are read-only.
--
-- Array-based placeholders (Tags, Entities, Authors) are expected to produce
-- multiple metadata entries per document during retain expansion.
-- ============================================================================

INSERT OR IGNORE INTO metadata (meta_key, meta_value, meta_generated_by) VALUES
  ('architxt-tags',                   '{tags}',                  'system'),
  ('architxt-entity-match-pattern',   '{entity-match-pattern}',  'system'),
  ('architxt-entities',               '{entities}',              'system'),
  ('architxt-document-size',          '{document-size}',         'system'),
  ('architxt-document-full-path',     '{document-full-path}',    'system'),
  ('architxt-file-name',              '{document-file-name}',    'system'),
  ('architxt-document-date',          '{document-date}',         'system'),
  ('architxt-author',                 '{document-author}',       'system');

-- ----------------------------------------------------------------------------
-- Mental model templates
-- Seeded from dev01: 4 base templates used by the Research prebuilt flow.
-- They are templates (mm_is_template='true') and expand per entity via
-- {entity-id}, {entity-name}, {entity-type} placeholders at runtime.
-- ----------------------------------------------------------------------------
INSERT OR IGNORE INTO mental_models (mm_ext_id, mm_name, mm_source_query, mm_dimension, mm_concatenation, mm_returns, mm_is_template, mm_template_role) VALUES
  ('architxt-capabilities-txt-{entity-id}', 'architxt-capabilities-txt-{entity-id}-{entity-name}', 'What are the major architectural capabilities for {entity-name} ({entity-type}:{entity-id})? List their responsibilities, purpose and business capability mapping.', 'capability', 'compile', 'narrative', 'true', 'user_entity_derived'),
  ('architxt-interface-found-{entity-id}', 'architxt-interface-found-{entity-id}-{entity-name}', 'What are the flows (apis, data, files and interface calls) into and out of {entity-name} ({entity-type}:{entity-id})? For found flows, describe them contextually. Return each contextual flow as a separate row.', 'interface-found', 'merge', 'graph-discovery', 'true', 'user_entity_derived'),
  ('architxt-interface-json-{entity-id}', 'architxt-interface-json-{entity-id}-{entity-name}', 'What are the flows (apis, data, files and interface calls) into and out of {entity-name} ({entity-type}:{entity-id})? For known flows, describe them contextually. Return each contextual flow as a separate row.', 'interface', 'compile', 'graph-known', 'true', 'user_entity_derived'),
  ('architxt-summary-txt-{entity-id}', 'architxt-summary-txt-{entity-id}-{entity-name}', 'Describe the core role that {entity-name} ({entity-type}:{entity-id}) plays in the architecture. Return a short summary and a table listing aspect and description.', 'summary', 'compile', 'narrative', 'true', 'user_entity_derived');

-- ----------------------------------------------------------------------------
-- Built-in prompt templates (v0.3.5 prompt/graph standardization)
-- ----------------------------------------------------------------------------
INSERT OR IGNORE INTO prompt_templates (pt_name, pt_mode, pt_description, pt_body, pt_fragments, pt_variables, pt_examples_heuristic, pt_is_builtin) VALUES
  ('narrative', 'narrative', 'Narrative-only output.', 'Answer the topic below as a focused Markdown narrative. Do not return a graph section.\\n\\n## Topic\\n\\n{{ARCHITXT_TOPIC}}\\n\\n## Source material\\n\\n{{ARCHITXT_CORPUS}}', '[]', '["ARCHITXT_TOPIC"]', NULL, 1),
  ('graph-known', 'graph-known', 'Graph-only output using known entities only.', 'Return only the graph section for the topic below. Use only entity ids from the provided catalog. Do not invent new entities.\\n\\n## Topic\\n\\n{{ARCHITXT_TOPIC}}\\n\\n## Source material\\n\\n{{ARCHITXT_CORPUS}}', '["output-format-graph.md","entity-catalog.md","entity-id-format.md","node-discovery-policy-known.md","edge-vocabulary.md","node-eligibility.md","label-rules.md","provenance-rules.md"]', '["ARCHITXT_TOPIC","ARCHITXT_ENTITIES","ARCHITXT_NODE_EXAMPLES"]', 'top-n', 1),
  ('graph-discovery', 'graph-discovery', 'Graph-only output allowing discovered nodes.', 'Return only the graph section for the topic below. Prefer known entities from the catalog; you may add found: nodes for persistent named architectural elements not in the catalog.\\n\\n## Topic\\n\\n{{ARCHITXT_TOPIC}}\\n\\n## Source material\\n\\n{{ARCHITXT_CORPUS}}', '["output-format-graph.md","entity-catalog.md","entity-id-format.md","node-discovery-policy-allowed.md","edge-vocabulary.md","node-eligibility.md","label-rules.md","provenance-rules.md"]', '["ARCHITXT_TOPIC","ARCHITXT_ENTITIES","ARCHITXT_NODE_EXAMPLES"]', 'top-n', 1),
  ('graph-discovered-only', 'graph-discovered-only', 'Graph-only output returning discovered nodes and edges only.', 'Return only the graph section for the topic below. Emit only discovered nodes and edges. Known entities may appear only as endpoints of discovered edges; do not return them as standalone nodes.\\n\\n## Topic\\n\\n{{ARCHITXT_TOPIC}}\\n\\n## Source material\\n\\n{{ARCHITXT_CORPUS}}', '["output-format-graph.md","entity-catalog.md","entity-id-format.md","node-discovery-policy-discovered-only.md","edge-vocabulary.md","node-eligibility.md","label-rules.md","provenance-rules.md"]', '["ARCHITXT_TOPIC","ARCHITXT_ENTITIES","ARCHITXT_NODE_EXAMPLES"]', 'top-n', 1),
  ('narrative-graph-discovered-only', 'narrative-graph-discovered-only', 'Narrative + graph returning discovered nodes and edges only.', 'Answer the topic below as a focused Markdown narrative. Then return a graph section containing only discovered nodes and edges. Known entities may appear only as endpoints of discovered edges; do not return them as standalone nodes.\\n\\n## Topic\\n\\n{{ARCHITXT_TOPIC}}\\n\\n## Source material\\n\\n{{ARCHITXT_CORPUS}}', '["output-format-narrative-graph.md","entity-catalog.md","entity-id-format.md","node-discovery-policy-discovered-only.md","edge-vocabulary.md","node-eligibility.md","label-rules.md","provenance-rules.md"]', '["ARCHITXT_TOPIC","ARCHITXT_ENTITIES","ARCHITXT_NODE_EXAMPLES"]', 'top-n', 1),
  ('narrative-graph-known', 'narrative-graph-known', 'Narrative + graph using known entities only.', 'Answer the topic below as a focused Markdown narrative. Then return a graph section. Use only entity ids from the provided catalog. Do not invent new entities.\\n\\n## Topic\\n\\n{{ARCHITXT_TOPIC}}\\n\\n## Source material\\n\\n{{ARCHITXT_CORPUS}}', '["output-format-narrative-graph.md","output-format-graph.md","entity-catalog.md","entity-id-format.md","node-discovery-policy-known.md","edge-vocabulary.md","node-eligibility.md","label-rules.md","provenance-rules.md"]', '["ARCHITXT_TOPIC","ARCHITXT_ENTITIES","ARCHITXT_NODE_EXAMPLES"]', 'top-n', 1),
  ('narrative-graph-discovery', 'narrative-graph-discovery', 'Narrative + graph allowing discovered nodes.', 'Answer the topic below as a focused Markdown narrative. Then return a graph section. Prefer known entities from the catalog; you may add found: nodes for persistent named architectural elements not in the catalog.\\n\\n## Topic\\n\\n{{ARCHITXT_TOPIC}}\\n\\n## Source material\\n\\n{{ARCHITXT_CORPUS}}', '["output-format-narrative-graph.md","output-format-graph.md","entity-catalog.md","entity-id-format.md","node-discovery-policy-allowed.md","edge-vocabulary.md","node-eligibility.md","label-rules.md","provenance-rules.md"]', '["ARCHITXT_TOPIC","ARCHITXT_ENTITIES","ARCHITXT_NODE_EXAMPLES"]', 'top-n', 1),
  ('sys_entity_summary', 'sys_entity_summary', 'System template: concise evidence-backed summary for one contextual-graph node.', 'You are summarising a single known architectural entity for an architecture graph.\\n\\n## Entity\\n\\n{{ARCHITXT_TOPIC}}\\n\\n## Instructions\\n\\nDescribe the core role that the entity plays in the architecture. Return the summary in the `narrative` field of the JSON envelope.\\n\\nRules:\\n- Use only facts supported by the source material.\\n- Do not invent aliases, artifacts, or related entities.\\n- Evidence is implicit in the source query scope; do not enumerate memory IDs inside the narrative.\\n- Keep the narrative short enough to fit within the model token budget.\\n\\n## Source material\\n\\n{{ARCHITXT_CORPUS}}', '["contextual-patch.md"]', '["ARCHITXT_TOPIC"]', NULL, 1),
  ('sys_entity_capabilities', 'sys_entity_capabilities', 'System template: capabilities table for one contextual-graph node.', 'You are listing the major architectural capabilities of a single known entity.\\n\\n## Entity\\n\\n{{ARCHITXT_TOPIC}}\\n\\n## Instructions\\n\\nReturn the capabilities in a single table named `capabilities` with columns `name`, `responsibility`, `purpose`, `business_capability_mapping`, and `evidence`.\\n\\nRules:\\n- Each capability must be a stable, high-level responsibility, not a one-off mention.\\n- `responsibility` describes what the entity does for this capability.\\n- `purpose` explains why the capability matters.\\n- `business_capability_mapping` places the capability in a business domain.\\n- `evidence` must be an array of memory IDs that support the capability.\\n- Do not include capabilities that are not backed by evidence.\\n\\n## Source material\\n\\n{{ARCHITXT_CORPUS}}', '["contextual-patch.md","output-format-table-contextual.md"]', '["ARCHITXT_TOPIC"]', NULL, 1),
  ('sys_edge_context', 'sys_edge_context', 'System template: characterize directed relationships between two contextual-graph nodes.', 'You are describing the directed interaction between two known entities in an architecture graph.\\n\\n## Relationship\\n\\n{{ARCHITXT_TOPIC}}\\n\\n## Instructions\\n\\nBoth endpoints already exist in the graph. Do not introduce new nodes. Return the interaction as a directed edge in `graph.edges`.\\n\\nRules:\\n- If the interaction is bidirectional, emit two edges with `from`/`to` swapped.\\n- Do not include edges to nodes that are not one of the two endpoints.\\n- Drop any edge that lacks evidence.\\n\\n## Source material\\n\\n{{ARCHITXT_CORPUS}}', '["contextual-patch.md","output-format-graph-contextual.md","edge-vocabulary.md","entity-id-format.md","provenance-rules.md"]', '["ARCHITXT_TOPIC"]', NULL, 1),
  ('sys_discovery_context', 'sys_discovery_context', 'System template: suggest new contextual-graph nodes and edges around a seed node.', 'You are discovering candidate entities and relationships around a seed entity in the corpus.\\n\\n## Seed\\n\\n{{ARCHITXT_TOPIC}}\\n\\n## Instructions\\n\\nReturn candidate nodes and edges in `graph.nodes` and `graph.edges`. This output is an internal working-graph input only; do not surface it as user-facing prose.\\n\\nRules:\\n- Candidate node IDs must use the `found:{slug}` form.\\n- Existing known nodes must use their canonical `TYPE:ID` id.\\n- Every candidate and edge must be backed by evidence.\\n- Do not return candidates that are already known canonical nodes.\\n\\n## Source material\\n\\n{{ARCHITXT_CORPUS}}', '["contextual-patch.md","output-format-graph-contextual.md","edge-vocabulary.md","entity-id-format.md","provenance-rules.md","node-discovery-policy-allowed.md"]', '["ARCHITXT_TOPIC"]', NULL, 1);
