-- ============================================================================
-- SYSTEM SEED DATA
-- ============================================================================
-- Idempotent inserts: INSERT OR IGNORE skips duplicates via the
-- UNIQUE(meta_key, meta_value) constraint on the metadata table.
-- These entries are tagged with generated_by='system' and are read-only.
--
-- Array-based placeholders (Tags, Entities, Authors) are expected to produce
-- multiple metadata entries per document during retain expansion.
-- ============================================================================

INSERT OR IGNORE INTO metadata (meta_key, meta_value, meta_generated_by) VALUES
  ('architxt-tags',                   '{tags}',                  'system'),
  ('architxt-entity-match-pattern',   '{entity-match-pattern}',  'system'),
  ('architxt-entities',               '{entities}',              'system'),
  ('architxt-document-size',          '{document-size}',         'system'),
  ('architxt-document-full-path',     '{document-full-path}',    'system'),
  ('architxt-file-name',              '{document-file-name}',    'system'),
  ('architxt-document-date',          '{document-date}',         'system'),
  ('architxt-author',                 '{document-author}',       'system');

-- ----------------------------------------------------------------------------
-- Built-in prompt templates (v0.3.5 prompt/graph standardization)
-- ----------------------------------------------------------------------------
INSERT OR IGNORE INTO prompt_templates (pt_name, pt_mode, pt_description, pt_body, pt_fragments, pt_variables, pt_examples_heuristic, pt_is_builtin) VALUES
  ('generic', 'generic', 'Universal template. Returns narrative + graph + tables based on user directives.', 'Answer the topic below.\\n\\n## Topic\\n\\n{{ARCHITXT_TOPIC}}\\n\\n## Source material\\n\\n{{ARCHITXT_CORPUS}}', '["contextual-patch.md","section-focus.md"]', '["ARCHITXT_TOPIC","ARCHITXT_NARRATIVE_FOCUS","ARCHITXT_GRAPH_FOCUS","ARCHITXT_TABLE_FOCUS"]', NULL, 1),
  ('sys_entity_summary', 'sys_entity_summary', 'System template: concise evidence-backed summary for one contextual-graph node.', 'You are summarising a single known architectural entity for an architecture graph.\\n\\n## Entity\\n\\n{{ARCHITXT_TOPIC}}\\n\\n## Instructions\\n\\nDescribe the core role that the entity plays in the architecture. Return the summary in the `narrative` field of the JSON envelope.\\n\\nRules:\\n- Use only facts supported by the source material.\\n- Do not invent aliases, artifacts, or related entities.\\n- Evidence is implicit in the source query scope; do not enumerate memory IDs inside the narrative.\\n- Keep the narrative short enough to fit within the model token budget.\\n\\n## Source material\\n\\n{{ARCHITXT_CORPUS}}', '["contextual-patch.md","section-focus.md"]', '["ARCHITXT_TOPIC","ARCHITXT_NARRATIVE_FOCUS","ARCHITXT_GRAPH_FOCUS","ARCHITXT_TABLE_FOCUS"]', NULL, 1),
  ('sys_entity_capabilities', 'sys_entity_capabilities', 'System template: capabilities table for one contextual-graph node.', 'Answer the topic below.\\n\\n## Topic\\n\\n{{ARCHITXT_TOPIC}}\\n\\n## Source material\\n\\n{{ARCHITXT_CORPUS}}', '["contextual-patch.md","section-focus.md"]', '["ARCHITXT_TOPIC","ARCHITXT_NARRATIVE_FOCUS","ARCHITXT_GRAPH_FOCUS","ARCHITXT_TABLE_FOCUS"]', NULL, 1),
  ('sys_edge_context', 'sys_edge_context', 'System template: characterize directed relationships between two contextual-graph nodes.', 'Answer the topic below.\\n\\n## Topic\\n\\n{{ARCHITXT_TOPIC}}\\n\\n## Source material\\n\\n{{ARCHITXT_CORPUS}}', '["contextual-patch.md","section-focus.md","edge-vocabulary.md","entity-id-format.md","provenance-rules.md"]', '["ARCHITXT_TOPIC","ARCHITXT_NARRATIVE_FOCUS","ARCHITXT_GRAPH_FOCUS","ARCHITXT_TABLE_FOCUS"]', NULL, 1),
  ('sys_discovery_context', 'sys_discovery_context', 'System template: suggest new contextual-graph nodes and edges around a seed node.', 'You are discovering candidate entities and relationships around a seed entity in the corpus.\\n\\n## Seed\\n\\n{{ARCHITXT_TOPIC}}\\n\\n## Instructions\\n\\nReturn candidate nodes and edges in `graph.nodes` and `graph.edges`. This output is an internal working-graph input only; do not surface it as user-facing prose.\\n\\nRules:\\n- Candidate node IDs must use the `found:{slug}` form.\\n- Existing known nodes must use their canonical `TYPE:ID` id.\\n- Every candidate and edge must be backed by evidence.\\n- Do not return candidates that are already known canonical nodes.\\n\\n## Source material\\n\\n{{ARCHITXT_CORPUS}}', '["contextual-patch.md","output-format-graph-contextual.md","edge-vocabulary.md","entity-id-format.md","provenance-rules.md","node-discovery-policy-allowed.md"]', '["ARCHITXT_TOPIC","ARCHITXT_NARRATIVE_FOCUS","ARCHITXT_GRAPH_FOCUS","ARCHITXT_TABLE_FOCUS"]', NULL, 1);

-- ----------------------------------------------------------------------------
-- Master bank settings defaults (non-bank-specific)
-- ----------------------------------------------------------------------------
INSERT OR IGNORE INTO bank_settings (bs_id, retain_mission, observations_mission, reflect_mission, disposition, retain_extraction_mode, retain_chunk_size) VALUES (1,
'For each specific, singular piece of information, capture exactly one of the following:\n\n1. COMPONENTS: A single system, service, database, or external integration. Use entity labels [[Name (ID)]] when present. Components by themselves (i.e. just being present) is NOT a fact.\n2. INTERFACES: One API endpoint, data format, file pattern, or parameter — not a list of endpoints. Extract each interface flow direction as a discreet, separate fact.\n3. DATA FLOWS: One directional relationship — which specific component produces data and which specific component consumes it. Use explicit language: sends to, receives from, exchanges with.\n4. RISKS & CONSTRAINTS: One performance limit, size limit, vendor gap, or regulatory requirement.\n5. SIZING: One data volume, collection size, or throughput figure.\n6. SYSTEM PURPOSE & CAPABILITIES: What business or technical capability the system provides, what problem it solves in the architecture, and what role it plays (e.g., canonical source, integration hub, customer-facing portal, reporting layer, data warehouse). If the source text states what would break or degrade if this system were unavailable, capture that as a separate purpose fact.\n\nRules:\n- DO NOT capture individual field names, column names, row values or field definitions unless there are directly related to an architectural component, interface, dataflow or decision.\n- Separate facts per component connections - e.g. If a component has 5 connections, extract 5 separate data-flow facts, not 1 summary fact.\n- Separate facts per interface - e.g. If a system exposes 3 API endpoints, extract 3 separate interface facts.\n- Separate facts per sizing, amounts, totals - e.g. If a table lists 4 sizing figures, extract 4 separate sizing facts.\n- If a system''s purpose or architectural role is described in the source text, extract it as a separate purpose fact. Do not combine purpose with identity or connection facts.\n- Each fact must contain exactly one specific piece of information.\n- Preserve [[Name (ID)]] bracket notation exactly. Do not paraphrase or rewrite entity references.\n\nOnly extract purpose and capability statements that are stated explicitly in the source text. If the document describes what a system does, what it stores, or what downstream processes depend on it, capture that verbatim as a purpose fact. Do not infer, extrapolate, or invent purpose facts — if the source text does not describe a system''s architectural role, do not create a purpose fact for it.',
'When consolidating related world facts into observations, follow these rules:\n\n1. Preserve [[Name (ID)]] bracket notation exactly. Observations must remain entity-tagged. Include the same [[Name (ID)]] labels from the source world facts so the observation is traversable in the entity graph.\n\n2. Synthesize, do not concatenate. Only create an observation when merging multiple related facts genuinely produces a richer insight or reveals a cross-system pattern. Do not create observations that merely join atomic facts with commas or "and" — leave those as separate world facts.\n\n3. Exclude temporal and procedural noise. Strip migration timelines, phase references ("before/after"), "intent", "recommendation", "should", and "may" language. Observations must state what is, not what is planned or advised.\n\n4. Prefer architectural relationships over restatements. Prioritize observations that describe cross-system data flows, dependency chains, or architectural trade-offs. Avoid observations that only restate identity, sizing, or deployment counts already captured in world facts.',
'You are a senior IT Architect. Your purpose is to surface architectural components, interfaces and interactions in a concise, accurate and consistent way.',
'{"empathy":1,"literalism":4,"skepticism":1}', 'verbose', 2000);
